baseURL = '/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[params]
    title = "Qoherent" 
    description = "Something here?"
    favicon = "../static/favicon"
    message = "RIAHUB COMING SOON!" 
    release = "June 20, 2025" 
    background = "" 

socialIcons = [
    {name = "twitter", url = "https://twitter.com/qoherent"},    
    {name = "github", url = "https://github.com/qoherent"},   
    {name = "linkedin", url = "https://www.linkedin.com/company/qoherent/"},
] 