baseURL = '/'
languageCode = 'en-us'
title = 'RIA Hub - Lets build intelligent radios together.'

[params]
    title = "" 
    description = "Let's build intelligent radios together."
    favicon = "favicon.ico"
    message = "RIA Hub - COMING SOON!" 
    release = "June 20, 2025" 
    background = "" 

socialIcons = [
    {name = "twitter", url = "https://twitter.com/qoherent"},    
    {name = "github", url = "https://github.com/qoherent"},   
    {name = "linkedin", url = "https://www.linkedin.com/company/qoherent/"},
] 