baseURL = 'https://qoherent.github.io/riahub_landing/'
languageCode = 'en-us'
title = 'RIAHUB - Lets build intelligent radios together.'

[params]
    title = "RIAHUB" 
    description = "Let's build intelligent radios together."
    favicon = "../static/favicon"
    message = "RIAHUB - COMING SOON!" 
    release = "June 20, 2025" 
    background = "" 

socialIcons = [
    {name = "twitter", url = "https://twitter.com/qoherent"},    
    {name = "github", url = "https://github.com/qoherent"},   
    {name = "linkedin", url = "https://www.linkedin.com/company/qoherent/"},
] 